version: '3.8'

services:
  raja-cepat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: raja-cepat-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=https://apirace.eurekagroup.id
    networks:
      - raja-cepat-network

networks:
  raja-cepat-network:
    driver: bridge
